# Generated by Django 4.2.7 on 2023-12-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('categoria', models.CharField(choices=[('novelas', 'Novelas'), ('suspenso', 'Suspenso'), ('historia', 'Historia'), ('test', 'Test')], max_length=50, verbose_name='Categoría')),
                ('ubicacion', models.CharField(max_length=20, verbose_name='Ubicación')),
                ('ejemplares_totales', models.IntegerField(default=0)),
                ('ejemplares_disponibles', models.IntegerField(default=0)),
                ('ejemplares_prestados', models.IntegerField(default=0)),
                ('ejemplares_reservados', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Datos_Libros',
            },
        ),
    ]
