# Generated by Django 4.2.7 on 2023-12-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appejemplares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={},
        ),
    ]
