# Generated by Django 4.2.7 on 2023-12-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_usuario', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('curso', models.CharField(max_length=20, verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Datos_Usuarios',
            },
        ),
    ]
