# Generated by Django 4.2.7 on 2023-12-08 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appejemplares', '0001_initial'),
        ('appusuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateTimeField(auto_now=True)),
                ('fecha_devolucion_calculada', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('flg_estado_prestamo', models.CharField(choices=[('0', 'Vigente'), ('1', 'Finalizado'), ('2', 'Devolución Atrasada')], default='0', max_length=10)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appejemplares.libro')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appusuarios.usuario')),
            ],
            options={
                'verbose_name': 'Datos_Prestamos',
            },
        ),
    ]
